# Generated by Django 4.0.2 on 2022-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('telegram_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(1, 'buy_admin'), (2, 'booking_admin'), (3, 'resume_admin')], max_length=100)),
            ],
        ),
    ]
