# Generated by Django 4.0.2 on 2022-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='type',
            field=models.CharField(choices=[('1', 'buy_admin'), ('2', 'booking_admin'), ('3', 'resume_admin')], max_length=1),
        ),
    ]
